### PR TITLE
change cgo readline to native goline

### PR DESCRIPTION
**Pull request by ezotrank**
It only draft commit, but code is already working. Next step to find alternative to readline history.

### CODE REVIEW

**Comment by Dieterbe** [comment]
a pure go readline-like library? that's awesome. been looking for something like this. unfortunetaly this looks a little to immature to switch at this point.

**Comment by ezotrank** [comment]
Why goline looks little immature? It's tiny project, but it work, and readline functionality is insignificant place in influx-cli, and it can always be replaced by another analog. And again, I think that main point is remove last cgo deps )

BTW, do you think about move this repo to official influxdb repo?

**Comment by Dieterbe** [comment]
their readme says:

> Very alpha quality right now. API will probably change and evolve.

**Comment by Dieterbe** [comment]
> BTW, do you think about move this repo to official influxdb repo?

i don't have strong opinions about this

**Comment by ezotrank** [comment]
Maybe be author of goline is perfectionist, and he can't bump version number to 1.0 until he hasn't wrote thousand tests =) I found some problem with history, but today or tomorrow I will fix it and make pull request.
And what about official influxdb repo, it's good for find new contributors. More contributors more features :)

**Comment by Dieterbe** [comment]
what's the problem exactly with depending on a library that uses cgo?

**Comment by ezotrank** [comment]
First of all need  installing some extra package by yum/apt get/brew, and next problem you can't use cross compile features. My opinion that if possible use pure go - use it. IMHO

**Pull request closed without merging**
